package io.legado.app.domain.model.settings

import io.legado.app.data.entities.BookGroup

data class BookshelfSettings(
    val bookGroupStyle: Int = 0,
    val hideEmptyGroups: Boolean = true,
    val bookshelfSort: Int = 0,
    val bookshelfSortOrder: Int = 1,
    val showUnread: Boolean = true,
    val showUnreadNew: Boolean = true,
    /** 是否在书架显示阅读进度（列表标签行百分比+进度条、网格封面底部进度条） */
    val showReadingProgress: Boolean = false,
    val showTip: Boolean = false,
    val showBookCount: Boolean = true,
    val showLastUpdateTime: Boolean = false,
    val showBookIntro: Boolean = false,
    val bookshelfShowIntro: Boolean = true,
    val bookshelfShowTag: Boolean = true,
    val bookshelfTagBorder: Boolean = false,
    val bookshelfShowLatestChapter: Boolean = true,
    val bookshelfIntroMaxLines: Int = 0,
    val showWaitUpCount: Boolean = false,
    val showBookshelfFastScroller: Boolean = false,
    val shouldShowExpandButton: Boolean = false,
    val bookshelfRefreshingLimit: Int = 0,
    val bookshelfLayoutModePortrait: Int = 1,
    val bookshelfLayoutGridPortrait: Int = 3,
    val bookshelfLayoutModeLandscape: Int = 1,
    val bookshelfLayoutGridLandscape: Int = 7,
    val bookshelfLayoutListPortrait: Int = 1,
    val bookshelfLayoutListLandscape: Int = 1,
    val bookshelfFolderLayoutModePortrait: Int = 1,
    val bookshelfFolderLayoutGridPortrait: Int = 3,
    val bookshelfFolderLayoutModeLandscape: Int = 1,
    val bookshelfFolderLayoutGridLandscape: Int = 7,
    val bookshelfFolderLayoutListPortrait: Int = 1,
    val bookshelfFolderLayoutListLandscape: Int = 1,
    val bookshelfGridLayout: Int = 0,
    val bookshelfLayoutCompact: Boolean = false,
    val bookshelfListCoverCenter: Boolean = true,
    val bookshelfListIntroBelowContent: Boolean = false,
    val bookshelfTicketStyle: Boolean = false,
    val bookshelfTicketDotted: Boolean = false,
    val bookshelfShowDivider: Boolean = true,
    val bookshelfTitleSmallFont: Boolean = false,
    val bookshelfTitleCenter: Boolean = true,
    val bookshelfTitleMaxLines: Int = 2,
    val bookshelfCoverShadow: Boolean = false,
    val bookshelfCardColor: Int = 0,
    val bookshelfCardColorDark: Int = 0,
    /** 书架卡片背景图（日/夜），配置后叠在卡片背景色之上；与容器背景图同一套九宫格规则 */
    val bookshelfCardImageLight: String? = null,
    val bookshelfCardImageDark: String? = null,
    /** 九宫格切分线 CSV（"npL,npR,npT,npB" 四角占比），由切图编辑器保存 */
    val bookshelfCardNineSliceLight: String? = null,
    val bookshelfCardNineSliceDark: String? = null,
    /** 九宫格图案缩放，日夜共用一个值；100% = 原图 1px 画 1 屏幕像素（与容器「图案大小」同基准） */
    val bookshelfCardNineScale: Float = 1f,
    val bookshelfGroupListStyle: Int = 0,
    val bookshelfGroupCoverCount: Int = 4,
    val bookshelfListCoverWidth: Int = 84,
    val bookshelfGridCoverWidth: Int = 120,
    val bookshelfSearchActionDirectToSearch: Boolean = true,
    /** 允许书架同时存在同名同作者同形态（文本/有声/漫画）的书；关闭时加入书架会替换已有那本 */
    val allowSameNameAuthorType: Boolean = false,
    val autoRefreshBook: Boolean = false,
    val saveTabPosition: Long = BookGroup.IdAll,
    /** 是否显示书架标签筛选行 */
    val showBookshelfTagFilter: Boolean = false,
    /** 书架标签筛选中选中的标签 ID 集合 */
    val selectedBookshelfTagIds: Set<Long> = emptySet(),
    /** 标签筛选行是否展开；长按分组按钮切换，进程重启后恢复 */
    val bookshelfTagFilterExpanded: Boolean = true,
)
